require("modules/starter")
require("modules/cmp-init")
require("modules/dap-init")
require("modules/fzf")
require("modules/lsp-init")
require("modules/pairs-init")
require("modules/statuswinbar")
require("modules/surround")
require("modules/term")
require("modules/treesitter-init")
require("modules/undotree")

require("config_autocmds")
require("config_functions")
require("config_keymaps")
