require("modules/starter")
require("modules/cmp-init")
require("modules/tree-init")
require("modules/treesitter-init")
require("modules/stay-init")
require("modules/task-init")
-- require("modules/telescope")
require("modules/fzf")
require("modules/undotree")
require("modules/statuswinbar")
require("modules/surround")
require("modules/lsp-init")
require("modules/term")
require("modules/gdb")
require("config_keymaps")
require("config_functions")
require("config_autocmds")
