-- require("impatient")
vim.loader.enable()
require("colors")
require("options")
require("config")
require("harpoon").setup({})
require("modules/cmp-init")
require("modules/tree-init")
require("modules/treesitter-init")
require("modules/stay-init")
require("modules/task-init")
require("modules/telescope")
require("modules/undotree")
require("plugins.make-flow")
require('colorizer').setup({}, { css = true; })
require('easyread').setup({})
require('mini.pairs').setup()
require("modules/statuswinbar")
require("modules/surround")
require("modules/lsp-init")
require("modules/term")
require("modules/gdb")
-- require("modules/null")
require("modules/starter")
require("oil").setup()
