local Plug = vim.fn["plug#"]
vim.call('plug#begin', '~/.local/share/nvim/plugged/')

Plug( 'feline-nvim/feline.nvim')
Plug( 'neovim/nvim-lspconfig')
Plug( 'vim-airline/vim-airline')
Plug( 'vim-airline/vim-airline-themes')
Plug( 'nvim-treesitter/nvim-treesitter')
-- "( Tim Pope plugins)
Plug( 'tpope/vim-surround')
Plug( 'tpope/vim-fugitive')
Plug( 'tpope/vim-commentary')
-- "( Completion plugins)
Plug( 'hrsh7th/cmp-nvim-lsp')
Plug( 'hrsh7th/cmp-buffer')
Plug( 'hrsh7th/cmp-path')
Plug( 'hrsh7th/cmp-cmdline')
Plug( 'hrsh7th/nvim-cmp')
-- "( Vsnip)
Plug( 'hrsh7th/cmp-vsnip')
Plug( 'hrsh7th/vim-vsnip')
-- "( Misc nice plugins)
Plug( 'Pocco81/true-zen.nvim')
Plug( 'shaunsingh/nord.nvim')
Plug( 'godlygeek/tabular')
Plug( 'preservim/vim-markdown')
Plug( 'ethanholz/nvim-lastplace')
-- "( Telescope )
Plug( 'nvim-lua/plenary.nvim')
Plug( 'nvim-telescope/telescope.nvim', { branch = '0.1.x' })
-- "( Nvim File tree 
Plug( 'kyazdani42/nvim-web-devicons' )
Plug( 'kyazdani42/nvim-tree.lua')
-- "( Various Themes)
Plug( 'mcchrish/zenbones.nvim')
Plug( 'rktjmp/lush.nvim')
Plug( 'tanvirtin/monokai.nvim')
vim.call('plug#end')
