name: Neovim Launch
run-name: Neovim Launch
on:
  push:
    branches: 
      - master
jobs:
  Launch:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Setup neovim
        run: ${{ github.workspace }}/bin/setup.sh
      - name: Does neovim launch without error?
        run: |
          nvim --headless +q 2> error_file
          if [[ $(grep "Error" error_file) ]]; then
            cat error_file
            exit 1
          else
            exit 0
          fi
